### ISSUE TITLE
what is `gamma_y`?

### ISSUE THREAD

**Issue by spinkney** [helske/walker#17]
In https://github.com/helske/walker/blob/392bafb4333b715ca4846dac7c0e0bbf64538d92/inst/stan/walker_lm.stan#L134 there's a gamma_y and it's called in the `walker_lm` code but is initialized to all 1s. It's not documented that you can pass this argument in. Just wondering what it does.

**Comment by helske** [comment]
That is "documented" in
https://github.com/helske/walker/blob/392bafb4333b715ca4846dac7c0e0bbf64538d92/R/walker.R#L46
The idea is similar to the one mentioned in the [walker paper](https://www.sciencedirect.com/science/article/pii/S235271102200022X)
![image](https://user-images.githubusercontent.com/1560448/178152336-7d9764c9-97bf-4e10-81c6-c0d066ce5d47.png)
but here the known sequence of gammas is related to the observational noise so that y_t ~N(. , (gamma_y * sigma_y)^2).

I should really improve the documentation of these, the description of `gamma` in `rw1` is actually not quite correct in terms of required dimension (`gamma` should be a matrix in case of multiple coefficients).
